# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'es'
    email_from: '%env(MAILER_FROM)%'
    recaptcha_secret_key: '%env(RECAPTCHA_SECRET_KEY)%'
    maintenance_file: '%kernel.project_dir%/.maintenance'
    matches_directory: '%kernel.project_dir%/public/uploads/matches'
    results_directory: '%kernel.project_dir%/public/uploads/results'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\EventListener\EncryptionSubscriber:
        tags:
            - { name: doctrine.event_subscriber, connection: default }
    App\EventListener\MaintenanceListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    # explicitly passing the access chanel logger
    App\Security\LoginFormAuthenticator:
        arguments:
            $accessLogger: '@monolog.logger.access'

    # explicitly passing the access chanel logger
    App\Security\AdminLoginFormAuthenticator:
        arguments:
            $accessLogger: '@monolog.logger.access'

    # explicitly passing the access chanel logger
    App\Security\PartyLoginFormAuthenticator:
        arguments:
            $accessLogger: '@monolog.logger.access'